### PR TITLE
Correct key name for session

### PR DESCRIPTION
**Pull request by zepouet**
Without no way to get {{accessToken}} in the templating model

Thanks a lot for this awesome example

### CODE REVIEW

**Comment by aesteve** [comment]
Thanks for the PR. Seems like it should be [`ACCESS_TOKEN`](https://github.com/aesteve/vertx-feeds/blob/39e2eae56dc1fec0a797fb4ad6bf2383acc4304d/src/main/java/io/vertx/examples/feeds/handlers/api/AuthenticationApi.java#L17), no ? Thus making it public.


I also should update to 3.4.0 btw.

**Comment by zepouet** [comment]
Yes it is exactly that : ACCESS_TOKEN
Perfect if you update to 3.4.0. I could do it if you want. So I could discover the changes.

Thanks a lot.

**Comment by aesteve** [comment]
Yes, feel free to do both changes, please ! 
Remember it's just a showcase project: there's nothing critical, you can just break pretty much anything.

It'd be cool to have someone else "view" in the code, also.

**Comment by zepouet** [comment]
Thanks Arnaud. 

One of my collegue will do a PR about update theme. We use material design and in a next step we will do a full SPA for your application. It is a good way to test and learn.

Thanks !

**Comment by aesteve** [comment]
I'm closing the PR since it has been fixed by #9 but many many thanks for pointing this out

**Pull request closed without merging**
